//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        public int userID { get; set; }
        public Nullable<System.DateTime> dayStart { get; set; }
        public Nullable<System.DateTime> dayEnd { get; set; }
        public Nullable<int> dailyHours { get; set; }
    
        public virtual User User { get; set; }
    }
}
